# Generated by Django 4.1.7 on 2023-03-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitems_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='item_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart'),
        ),
    ]
