# Generated by Django 4.1.7 on 2023-03-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_item_id_cartitems_id_alter_cartitems_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
